version: 2

updates:

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    labels:
      - dependabot

  - package-ecosystem: npm
    directory: "/src/recipebook.web"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - dependabot

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - dependabot
