version: 2

registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:

  - package-ecosystem: nuget
    directory: "/"
    registries:
      - public-nuget
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    labels:
      - dependabot

  - package-ecosystem: npm
    directory: "/src/recipebook.web"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - dependabot

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - dependabot
