name: recipe-book

volumes:
  postgres:
  valkey:

services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  valkey:
    container_name: valkey
    image: valkey/valkey:8.0.2
    ports:
      - "6379:6379"
    volumes:
      - valkey:/data
