name: recipe-book

services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dashboard:
    container_name: dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888"
      - "4317:18889"
      - "4318:18890"
