name: recipe-book

volumes:
  pgdata:
  dfdata:

services:
  postgres:
    container_name: postgres
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dragonfly:
    container_name: dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dfdata:/data
