name: recipe-book-db

networks:
  mongo-network:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:7.0.12-ubuntu2204
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      RECIPE_BOOK_API_USER: ${RECIPE_BOOK_API_USER}
      RECIPE_BOOK_API_PWD: ${RECIPE_BOOK_API_PWD}
      RECIPE_BOOK_API_DATABASE: ${RECIPE_BOOK_API_DATABASE}
      RECIPE_BOOK_API_COLLECTION: ${RECIPE_BOOK_API_COLLECTION}
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db/mongo/db:/data/db:rw
      - ./db/mongo/config:/data/configdb:rw
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    ports:
      - 8881:8081
    networks:
      - mongo-network
