name: recipe-book

volumes:
  pgdata:

services:
  postgres:
    container_name: postgres
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
