name: Recipe Book

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: .NET CI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    env:
      RECIPE_BOOK_API_USER: ${{ secrets.RECIPE_BOOK_API_USER }}
      RECIPE_BOOK_API_PWD: ${{ secrets.RECIPE_BOOK_API_PWD }}
      RECIPE_BOOK_API_DATABASE: ${{ secrets.RECIPE_BOOK_API_DATABASE }}
      RECIPE_BOOK_API_COLLECTION: ${{ secrets.RECIPE_BOOK_API_COLLECTION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Cache .NET packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-NuGet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-NuGet-

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          global-json-file: true

      - name: Update Workloads
        run: dotnet workload update

      - name: Install Aspire Workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        run: dotnet restore RecipeBook.sln

      - name: Build the application
        run: dotnet build RecipeBook.sln --configuration Release --no-restore

      - name: Test the application
        run: dotnet test RecipeBook.sln --configuration Release --no-build --verbosity normal --collect "XPlat Code Coverage" --results-directory ./coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '45 45'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          recreate: true
          path: code-coverage-results.md
